# Generated by Django 3.2 on 2022-06-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_oudimage_oud'),
    ]

    operations = [
        migrations.AddField(
            model_name='oudimage',
            name='is_main',
            field=models.BooleanField(blank=True, default=False, verbose_name='Main Image'),
            preserve_default=False,
        ),
    ]
