# Generated by Django 3.2 on 2022-06-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_oudimage_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oud',
            name='maker',
        ),
        migrations.AddField(
            model_name='oud',
            name='maker',
            field=models.ManyToManyField(to='gallery.Maker'),
        ),
    ]
