# Generated by Django 3.0.5 on 2020-04-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200424_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='original_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('sr', 'Serbian'), ('ar', 'Arabic'), ('cn', 'Chinese'), ('sw', 'Swedish'), ('ak', 'Akkadian')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
