# Generated by Django 3.0.5 on 2020-04-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200424_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('sr', 'Serbian'), ('ar', 'Arabic'), ('cn', 'Chinese'), ('sw', 'Swedish'), ('ak', 'Akkadian'), ('la', 'Latin')], max_length=2),
        ),
        migrations.AlterField(
            model_name='title',
            name='original_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('sr', 'Serbian'), ('ar', 'Arabic'), ('cn', 'Chinese'), ('sw', 'Swedish'), ('ak', 'Akkadian'), ('la', 'Latin')], max_length=2),
        ),
        migrations.AlterField(
            model_name='title',
            name='translators',
            field=models.ManyToManyField(blank=True, to='books.Translator'),
        ),
    ]
