# Generated by Django 3.0.5 on 2020-04-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200424_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('sr', 'Serbian'), ('ar', 'Arabic'), ('cn', 'Chinese'), ('sw', 'Swedish'), ('ak', 'Akkadian'), ('la', 'Latin'), ('es', 'Spanish')], max_length=2),
        ),
        migrations.AlterField(
            model_name='title',
            name='original_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('sr', 'Serbian'), ('ar', 'Arabic'), ('cn', 'Chinese'), ('sw', 'Swedish'), ('ak', 'Akkadian'), ('la', 'Latin'), ('es', 'Spanish')], max_length=2),
        ),
    ]
