# Generated by Django 3.0.5 on 2021-06-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200503_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('sr', 'Serbian'), ('ar', 'Arabic'), ('cn', 'Chinese'), ('sw', 'Swedish'), ('ak', 'Akkadian'), ('la', 'Latin'), ('es', 'Spanish'), ('fa', 'Persian'), ('el', 'Greek'), ('ru', 'Russian'), ('pt', 'Portuguese'), ('tr', 'Turkish'), ('it', 'Italian')], max_length=2),
        ),
        migrations.AlterField(
            model_name='title',
            name='original_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('sr', 'Serbian'), ('ar', 'Arabic'), ('cn', 'Chinese'), ('sw', 'Swedish'), ('ak', 'Akkadian'), ('la', 'Latin'), ('es', 'Spanish'), ('fa', 'Persian'), ('el', 'Greek'), ('ru', 'Russian'), ('pt', 'Portuguese'), ('tr', 'Turkish'), ('it', 'Italian')], max_length=2),
        ),
    ]
