# Generated by Django 3.0.5 on 2021-06-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20210622_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, default='.', max_length=200),
            preserve_default=False,
        ),
    ]
