# Generated by Django 3.0.5 on 2021-06-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20210622_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='arabic_definite_article',
            field=models.BooleanField(default=False),
        ),
    ]
