# Generated by Django 2.2.12 on 2021-01-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer_name_en', models.CharField(max_length=50)),
                ('composer_name_ar', models.CharField(max_length=50)),
                ('composer_birth_place_en', models.CharField(max_length=50)),
                ('composer_birth_place_ar', models.CharField(max_length=50)),
                ('composer_birth_year', models.SmallIntegerField(blank=True)),
                ('composer_birth_month', models.SmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'Febraury'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('composer_birth_day', models.SmallIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComposerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer_image', models.ImageField(upload_to='compositions/composers/images/')),
                ('profile_image', models.BooleanField(default=False)),
                ('image_description_en', models.CharField(max_length=50)),
                ('image_description_ar', models.CharField(max_length=50)),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compositions.Composer')),
            ],
        ),
    ]
