# Generated by Django 2.2.12 on 2021-01-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composer',
            old_name='composer_name_ar',
            new_name='composer_last_name_ar',
        ),
        migrations.RenameField(
            model_name='composer',
            old_name='composer_name_en',
            new_name='composer_last_name_en',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='composer_birth_place_ar',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='composer_birth_place_en',
        ),
        migrations.AddField(
            model_name='composer',
            name='composer_birth_city_ar',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='composer',
            name='composer_birth_city_en',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='composer',
            name='composer_birth_country_ar',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='composer',
            name='composer_birth_country_en',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='composer',
            name='composer_birth_locality_ar',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='composer',
            name='composer_birth_locality_en',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='composer',
            name='composer_death_day',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], null=True),
        ),
        migrations.AddField(
            model_name='composer',
            name='composer_death_month',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'Febraury'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AddField(
            model_name='composer',
            name='composer_death_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='composer',
            name='composer_first_name_ar',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='composer',
            name='composer_first_name_en',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='composer',
            name='composer_middle_name_ar',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='composer',
            name='composer_middle_name_en',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='composer',
            name='composer_birth_day',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], null=True),
        ),
        migrations.AlterField(
            model_name='composer',
            name='composer_birth_month',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'Febraury'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AlterField(
            model_name='composer',
            name='composer_birth_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
