# Generated by Django 2.2.12 on 2021-01-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0003_auto_20210110_2050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComposerImages',
            new_name='ComposerImage',
        ),
    ]
