# Generated by Django 3.1 on 2021-07-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0005_composition_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='maqam_ar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='maqam_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
