# Generated by Django 3.1 on 2021-08-02 16:12

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('compositions', '0008_auto_20210802_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='Comment',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='comment', to='cms.placeholder'),
        ),
    ]
