# Generated by Django 3.1 on 2021-09-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0009_score_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='Comment',
        ),
    ]
