# Generated by Django 3.1 on 2021-09-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0010_remove_score_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='title_ar',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='composition',
            name='title_en',
            field=models.CharField(max_length=150),
        ),
    ]
