# Generated by Django 3.1 on 2022-01-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0012_composer_arabic_definite_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rhythm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rhythm_en', models.CharField(blank=True, max_length=50, null=True)),
                ('rhythm_ar', models.CharField(blank=True, max_length=50, null=True)),
                ('rhythm_svg', models.FileField(upload_to='compositions/rhythms/')),
            ],
        ),
    ]
