# Generated by Django 3.2 on 2022-08-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0015_auto_20220829_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='abc_score',
        ),
    ]
