# Generated by Django 3.2 on 2022-10-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20220620_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lesson Order'),
        ),
    ]
