# Generated by Django 2.2.12 on 2020-12-23 02:11

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABCscore',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='abc_scores_abcscore', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(default='Guest', max_length=50)),
                ('abctxt', filer.fields.file.FilerFileField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.File', verbose_name='file')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
