# Generated by Django 3.2 on 2022-10-21 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abc_scores', '0004_abcscore_abc_score_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abcscore',
            name='abctxt',
        ),
    ]
